language: generic # optional, just removes the language badge

services:
  - docker

cache:
  directories:
    - $HOME/.ccache

env:
  global:
    - CCACHE_DIR=$HOME/.ccache
  matrix:
    - ROS_DISTRO="bouncy"
    - ROS_DISTRO="crystal"


install:
  - git clone --depth=1 https://github.com/ipa-mdl/industrial_ci.git .ci_config -b colcon
script:
  - .ci_config/travis.sh
